[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "latest"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

[functions]
  node_bundler = "esbuild"